### ISSUE TITLE
@rultor : Release and merge Request for Rultor

### ISSUE THREAD

**Issue by LaurentTardif** [LaurentTardif/mavenTraining#1]
@rultor hello

**Comment by LaurentTardif** [comment]
@rultor status

**Comment by LaurentTardif** [comment]
@rultor merge

**Comment by LaurentTardif** [comment]
@rultor merge Update Readme for rotor demo

**Comment by yegor256** [comment]
@LaurentTardif try to call it again. when you're changing the messages, rultor can't re-read them again. post a new one

**Comment by LaurentTardif** [comment]
thanks for the tip

**Comment by LaurentTardif** [comment]
@rultor merge Update Readme for rotor demo

**Comment by LaurentTardif** [comment]
@rultor merge Update Readme for rotor demo

**Comment by LaurentTardif** [comment]
@rultor release, tag=`1.0.0`

**Comment by LaurentTardif** [comment]
@rultor release, tag=1.0.1

**Comment by LaurentTardif** [comment]
@rultor release, tag=1.0.1

**Comment by LaurentTardif** [comment]
@rultor release, tag=`1.0.1`

**Comment by LaurentTardif** [comment]
@rultor release, tag=`1.0.1`

**Comment by LaurentTardif** [comment]
@rultor release, tag=`1.0.1`

**Comment by LaurentTardif** [comment]
@rultor release, tag=`1.0.2`

**Comment by LaurentTardif** [comment]
@rultor release, tag=`1.0.2`

**Comment by LaurentTardif** [comment]
Fixed, I will use an issue per release
